apiVersion: buildimage.buildimage/v1
kind: Builder
metadata:
  name: build-test
spec:
  config:
    IsMinio: true
    minio:
      endpoint: minio.fzzn-system.svc:9000
      forcePathStyle: testpath
      bucket: dyg-fzzn
      codeName: testfile
    newImageName: fzzn-test1
    newTag: v1
    dockerfileName: file-test
    backLimit: 3


